<?php

namespace App\Console;

use App\Console\Commands\BrokenFlowsCommand;
use App\Console\Commands\InsideTokenRefresherCommand;
use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Foundation\Console\Kernel as ConsoleKernel;

/**
 * Class Kernel
 * @package App\Console
 */
class Kernel extends ConsoleKernel {

    /**
     * The Artisan commands provided by your application.
     *
     * @var array
     */
    protected $commands = [
        Commands\FillStornoOrderStatuses::class,
        Commands\GaDeleteAndStartHistory::class,
        InsideTokenRefresherCommand::class,
        BrokenFlowsCommand::class
            // Commands\Inspire::class,
    ];

    /**
     * Define the application's command schedule.
     *
     * @param  \Illuminate\Console\Scheduling\Schedule  $schedule
     * @return void
     */
    protected function schedule(Schedule $schedule) {

        // $schedule->command('inspire')
        //          ->hourly();
    }

    public function handle($input, $output = null)
    {
        return parent::handle($input, $output); // TODO: Change the autogenerated stub
    }

}
