<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace App\Http\Controllers\OrderAlert\Search;

use App\Http\Controllers\Controller;
use Monkey\Breadcrump\BreadcrumbItem;

/**
 * Description of HomepageController
 *
 * @author Tomas
 */
class BaseController extends Controller {

    public function getIndex() {
        // return "TEST";
    }

//    protected function breadcrumbBeforeAction($parameters = array())
//    {
//        $breadcrumb = parent::breadcrumbBeforeAction($parameters); // TODO: Change the autogenerated stub
//        $breadcrumb->addBreadcrumbItem(new BreadcrumbItem('order-alert', 'Order Alert', \Monkey\action(IndexController::class)));
//        return $breadcrumb;
//    }
}
