<?php

namespace App\Http\Controllers\Open\ImportFlow\Graph;


use Illuminate\Support\Facades\Input;
use Monkey\View\View;

class QueuesJobsInTimeHistoryController extends BaseController {

    public function getIndex() {
        parent::getIndex(); // TODO: Change the autogenerated stub
        View::share("dayCount", Input::get("day_count", 2));
    }

}