<?php

namespace App\Http\Controllers\OrderAlert;


use App\Http\Controllers\Controller;
use Monkey\Breadcrump\BreadcrumbItem;

class BaseController extends Controller {

    protected function breadcrumbBeforeAction($parameters = array())
    {
        $breadcrumb = parent::breadcrumbBeforeAction($parameters); // TODO: Change the autogenerated stub
        $breadcrumb->addBreadcrumbItem(new BreadcrumbItem('order-alert', 'Order Alert', \Monkey\action(IndexController::class)));
        return $breadcrumb;
    }
}